- app/application/uses_cases/status.py
> Fix ride status

- .github/workflows/fly.yml
- fly.toml
Configure auto-deployment in Github Actions and set build Dockerfile.
---
> Minor changes

- Dockerfile
Reconfigure Dockerfile in entrypoint.
---
> Minor change in Dockerfile

- .github/workflows/ec2.yml
> Reimplement deploy in AWS

- Dockerfile
- README.md
> Minor changes in Dockerfile

- Dockerfile
> Fix copy files in Dockerfile

- fly.toml
> Set internal port in deployment

- app/application/uses_cases/automobile.py
- app/domain/models.py
- app/domain/services/automobile.py
- app/infrastructure/repository/automobile.py
- app/presentation/api/user_management_system/__init__.py
- app/presentation/api/user_management_system/automobile.py
- app/presentation/api/user_management_system/driver.py
- app/presentation/schemes/__init__.py
Please provide a concise summary of the changes included in this pull request, detailing the implemented features, resolved issues, and any other relevant information. Include any necessary context and rationale behind the changes.
List any new dependencies required by this change, specifying why they are necessary.
- [*] New Feature - Introduces new functionality without breaking changes.
---
> Initial commit from autobile branch

- app/core/__init__.py
- app/core/enum.py
- app/core/exception/__init__.py
- app/core/exception/handler.py
- app/core/types.py
- app/domain/services/automobile.py
- app/exception_handler.py
- app/presentation/api/__init__.py
- app/presentation/schemes/__init__.py
- main.py
Exception handler added to all routes and standardized.
---
> Exception handler

- app/infrastructure/repository/user.py
- app/presentation/schemes/auth.py
> Implemented methods

- app/application/uses_cases/auth.py
- app/infrastructure/repository/user.py
- app/presentation/api/user_management_system/user.py
Add methods for token validation and user profile fetching.
---
> Add Token validation and user profile fetching

- app/application/uses_cases/auth.py
- app/core/enum.py
- app/domain/models/__init__.py
- app/presentation/api/auth.py
- app/presentation/api/user_management/user.py
- app/presentation/schemes/__init__.py
> Role in UserResponse model

- app/presentation/api/__init__.py
- app/presentation/api/health.py
- app/presentation/api/v1/travel_match_network/__init__.py
- app/presentation/api/v1/travel_match_network/auth_travel.py
- app/presentation/api/v1/travel_match_network/rate.py
- app/presentation/api/v1/travel_match_network/status/socket.py
- app/presentation/api/v1/travel_match_network/travel.py
- app/presentation/api/v1/user_management/automobile.py
- app/presentation/api/v1/user_management/driver.py
- app/presentation/api/v1/user_management/user.py
- app/presentation/schemes/__init__.py
- app/presentation/schemes/websocket.py
> Format files

- Dockerfile
- app/core/__init__.py
- docker-compose.yaml
> Fix CORS and ports

- app/infrastructure/repository/travels/schedule.py
> Fix filtering query in NeoModel

- app/infrastructure/repository/travels/schedule.py
> Fixing filter queries in Neomodel

- app/core/exception/__init__.py
- app/domain/services/auth/__init__.py
> Fix exception and auth credentials

- app/core/exception/__init__.py
- app/core/utils/scheme_json/__init__.py
- app/domain/models/__init__.py
- app/domain/services/schedule.py
- app/infrastructure/repository/travels/schedule.py
- app/presentation/schemes/travels/__init__.py
> Fix exceptions credentials

- app/application/uses_cases/schedule.py
- app/core/utils/scheme_json/__init__.py
- app/domain/models/__init__.py
- app/domain/services/schedule.py
- app/infrastructure/repository/travels/schedule.py
- app/presentation/schemes/travels/__init__.py
> Implemented seats in travel schedule

- app/application/uses_cases/schedule.py
- app/core/utils/scheme_json/__init__.py
- app/infrastructure/repository/travels/ride.py
> Fix location data

- app/presentation/schemes/travels/__init__.py
> Fix price in scheme

- app/application/uses_cases/schedule.py
> Scheme fix max passengers (and minor changes)

- app/application/uses_cases/schedule.py
> Fix travel request
